<?php

declare(strict_types=1);
require_once __DIR__.'/../includes/funcoes.php';require_once __DIR__.'/../includes/conexao.php';require_once __DIR__.'/../includes/pdf_simples.php';exigirAdministrador();
$tipo=(string)($_GET['tipo']??'');if(!in_array($tipo,['candidatos','empresas','selecoes'],true))redirecionar('admin/relatorios.php');
$inicio=(string)($_GET['inicio']??date('Y-01-01'));$fim=(string)($_GET['fim']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$inicio))$inicio=date('Y-01-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$fim))$fim=date('Y-m-d');if($inicio>$fim){[$inicio,$fim]=[$fim,$inicio];}
$periodo='Período: '.date('d/m/Y',strtotime($inicio)).' a '.date('d/m/Y',strtotime($fim)).' - Gerado em '.date('d/m/Y H:i');$secoes=[];
if($tipo==='candidatos'){$titulo='Relatório de candidatos';$q=$pdo->prepare("SELECT c.nome_completo,c.telefone,u.email,cid.nome cidade,cid.uf,COALESCE(cu.titulo_profissional,'Currículo não publicado') titulo,EXISTS(SELECT 1 FROM experiencias e WHERE e.candidato_id=c.id AND e.emprego_atual=1) trabalhando FROM candidatos c JOIN usuarios u ON u.id=c.usuario_id JOIN cidades cid ON cid.id=c.cidade_id LEFT JOIN curriculos cu ON cu.candidato_id=c.id WHERE c.criado_em BETWEEN ? AND DATE_ADD(?,INTERVAL 1 DAY) ORDER BY cid.nome,c.nome_completo");$q->execute([$inicio,$fim]);$dados=$q->fetchAll();$linhas=[];foreach($dados as $d)$linhas[]=$d['nome_completo'].' | '.$d['titulo'].' | '.$d['cidade'].'-'.$d['uf'].' | '.($d['trabalhando']?'Trabalhando':'Sem vínculo atual').' | '.$d['email'].' | '.$d['telefone'];$secoes[]=['titulo'=>'Candidatos cadastrados ('.count($dados).')','linhas'=>$linhas?:['Nenhum registro no período.']];}
elseif($tipo==='empresas'){$titulo='Relatório de empresas';$q=$pdo->prepare("SELECT e.razao_social,e.nome_fantasia,e.cnpj,e.responsavel_nome,u.email,u.status,cid.nome cidade,cid.uf FROM empresas e JOIN usuarios u ON u.id=e.usuario_id JOIN cidades cid ON cid.id=e.cidade_id WHERE e.criado_em BETWEEN ? AND DATE_ADD(?,INTERVAL 1 DAY) ORDER BY e.razao_social");$q->execute([$inicio,$fim]);$dados=$q->fetchAll();$linhas=[];foreach($dados as $d)$linhas[]=($d['nome_fantasia']?:$d['razao_social']).' | CNPJ '.$d['cnpj'].' | '.$d['cidade'].'-'.$d['uf'].' | Status: '.$d['status'].' | Responsável: '.$d['responsavel_nome'].' | '.$d['email'];$secoes[]=['titulo'=>'Empresas cadastradas ('.count($dados).')','linhas'=>$linhas?:['Nenhum registro no período.']];}
else{$titulo='Relatório de seleções e contratações';$q=$pdo->prepare("SELECT c.nome_completo,COALESCE(e.nome_fantasia,e.razao_social) empresa,se.status,se.selecionado_em FROM selecoes_empresas se JOIN candidatos c ON c.id=se.candidato_id JOIN empresas e ON e.id=se.empresa_id WHERE se.selecionado_em BETWEEN ? AND DATE_ADD(?,INTERVAL 1 DAY) ORDER BY se.selecionado_em DESC");$q->execute([$inicio,$fim]);$dados=$q->fetchAll();$linhas=[];foreach($dados as $d)$linhas[]=$d['nome_completo'].' | Empresa: '.$d['empresa'].' | Status: '.ucfirst($d['status']).' | '.date('d/m/Y H:i',strtotime($d['selecionado_em']));$secoes[]=['titulo'=>'Resultados registrados ('.count($dados).')','linhas'=>$linhas?:['Nenhum registro no período.']];}
$pdf=gerarPdfSimples($titulo,$periodo,$secoes);$arquivo='emprega-jf-'.$tipo.'-'.date('Ymd').'.pdf';header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$arquivo.'"');header('Content-Length: '.strlen($pdf));header('Cache-Control: private, max-age=0, must-revalidate');echo $pdf;exit;
